version: '3.8'

services:
  shopilot-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_NUC_IP=192.168.0.100
      - NEXT_PUBLIC_ROSBRIDGE_PORT=9090
    restart: unless-stopped
    stdin_open: true
    tty: true

networks:
  default:
    driver: bridge